title: zukini - creative thoughtful sustainability
email: "hello@zukini.co.uk"
description: Creative thoughtful sustainability - coming soon the new zukini website.
baseurl: ""
url: "http://zukini.co.uk"
twitter_username: rajivshah
copyright: ZUKINI 2015
collections:
  - vbmenu
  - veggiebite
  - interviews
  - bakednotfried
sass:
  style: ""
markdown: kramdown
