title: zukini - creative thoughtful sustainability
email: "hello@zukini.co.uk"
description: Creative thoughtful sustainability
baseurl: ""
url: "http://zukini.co.uk"
twitter_username: rajivshah
copyright: ZUKINI 2016


collections:
  - vbmenu
  - veggiebite
  - interviews
  - bakednotfried
  
sass:
  style: compressed
  
markdown: kramdown
