# Site settings
title: zukini - creative thoughtful sustainability
email: hello@zukini.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Creative thoughtful sustainability - coming soon the new zukini website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zukini.co.uk" # the base hostname & protocol for your site
twitter_username: rajivshah
copyright: ZUKINI 2015

collections:
 - vbmenu
 - veggiebite
 - interviews
 - bakednotfried
 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  
sass:
  style: compressed
 

# Build settings
markdown: kramdown