# Site settings
title: zukini - creative thoughtful sustainability
email: your-hello@zukini.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Creative thoughtful sustainability - coming soon the new zukini website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
